### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by AirTechWick** [theta360developers/theta-client-guide#43]
https://airtechwick.github.io/grim-docs/

As shown on my personal mod guide website 
I have several suggestions:
- Sharable Search, allows people to share their search
- Light/Dark Mode for site
- Giscus Commenting System, can choose which pages have comments on them or have all pages with comments, uses github discussions to store all the comments and auto generates discussions.
- Link to Repo at the top right with live Repo Stars and Forks data shown
- Footer Navigation to previous or next page
- Pencil Edit Symbol, Easy contribution for people not used to git/github, it takes them directly to the github file and you don't need to download anything other than have a github account. It auto forks and branches and people send in their pull request after finish editing.
![image](https://user-images.githubusercontent.com/82003999/230950779-ce71eea0-245c-44d3-ac57-737eb45e9c02.png)

- Back to Top button shows up, when you scroll down

![image](https://user-images.githubusercontent.com/82003999/230950050-fdcab3cf-7f95-4834-a2b3-57b8d488b3d2.png)

**Comment by jcasman** [comment]
Priorities, IMO, should be:

* Pencil Edit Symbol - since getting outside contributions from the community could be good

* Giscus Commenting System - since making comments is also a form of contributing, requires less effort than a pull request

Secondary:

* Footer Navigation - since it might increase page views

* Light/Dark Mode for site - possibly useful for users who are up late

Do not include:

* Link to Repo at the top right with live Repo Stars and Forks data shown - super cool but i think our numbers will be low

* Sharable Search, allows people to share their search - i don't think people will use this

**Comment by AirTechWick** [comment]
Okay 👍
